source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '14.0'
inhibit_all_warnings!


target 'zebra-look' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 
  pod 'MJRefresh'
  pod 'Kingfisher'
  pod 'DZNEmptyDataSet'
  pod 'Alamofire', '~> 5.4'
  pod 'SnapKit', '~> 5.0.0'
  pod 'KakaJSON', '~> 1.1.2'
  pod 'IQKeyboardManagerSwift'
  
  pod 'FDFullscreenPopGesture', '1.1'

end
